### ISSUE TITLE
Update to v0.3.0 TO DO

### ISSUE THREAD

**Issue by lorderikir** [monPlan/AppleSeed#32]
- [x] Move **Default** Configuration Classes to `org.monplan.config`
    - [x] Moved CORS Configuration
- [x] Move _Model_, _Controller_, _Service_ and _Repository_ Template Classes to `org.monplan.interfaces`
- [x] Improve Documentation on Building on the MonPlan Classes (See #40)
- [x] Look at Tokenization and supporting of OAuth Tokens (See #48)
- [x] Pagination Support
- [x] Setup Auto-Configuration for Swagger
- [x] Moved `Application` and `ServletInitilizer` to `/src/main/java`
- [ ] Implement Logging in base MonPlan classes
- ~[ ] automate backups to GCS of DataStore models (See #65)~
- [x] Add Substring Search
- [x] Bug fix to support Google Issue #62

**Comment by lorderikir** [comment]
We can look at pagination support [here](https://ankushs92.github.io/tutorial/2016/05/03/pagination-with-spring-boot.html)

**Comment by lorderikir** [comment]
Google Issue #64571896 - a fix has been deployed but not in production

**Comment by lorderikir** [comment]
V 0.3.0 is Deployed
